name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PAT }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t myapp:latest -f db-connect-streamlit/Dockerfile .

      - name: Generate Random Image Tag
        id: generate_tag
        run: echo "::set-output name=TAG::$(date +%s)"

      - name: Push Docker image
        run: |
          docker tag myapp:latest $DOCKER_USERNAME/myapp:${{ steps.generate_tag.outputs.TAG }}
          docker push $DOCKER_USERNAME/streamlitweb:${{ steps.generate_tag.outputs.TAG }}
