name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t minha-aplicacao-streamlit:latest -f db-connect-streamlit/Dockerfile .


      - name: Log in to Docker Hub with PAT
        run: |
          echo ${{ secrets.DOCKER_PAT }} | docker login -u kozato --password-stdin
          docker push minha-aplicacao-streamlit:latest
