name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
          repository: kozato/githubkozato
          tags: latest, ${{ github.run_number }}

      - name: Build the Docker image
        run: docker build -t streamlitwebdblink:latest -f db-connect-streamlit/Dockerfile .

      #- name: Push Docker image
      #  run: docker push kozato/streamlitwebdblink:latest
